baseURL = 'https://gytxtx.top/'
languageCode = 'zh-CN'
title = 'Project for Saiba Midori'
theme = 'midori'

disableKinds = ["taxonomy", "term", "RSS"]

[caches]
  [caches.images]
    dir = ':cacheDir/images'

